# bStats (https://bStats.org) collects some basic information for plugin authors, like how
# many people use their plugin and their total player count. It's recommended to keep bStats
# enabled, but if you're not comfortable with this, you can turn this setting off. There is no
# performance penalty associated with having metrics enabled, and data sent to bStats is fully anonymous.

# If the same players sends a message after x seconds it will reset with their name attached again
# [19:03:04] <SkinnyJeans> This is an example for you
# [19:03:13] Which will hopefully help you better understand
# [19:03:18] What I'm trying to say
# [19:05:28] <SkinnyJeans> I sent this 120+ seconds later
seconds: 120

# Will use normal formatting once the same player has sent a message x times
max-contextual-count: 5

# To custom format chat messages
# Default formats are {player} and {message}, PAPI can be used for others and & for custom formatting
# format: "<&c&l{player}&r> %vault_prefix% {message}"
contextual-format: "{message}"